version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:80'
    depends_on:
      backend:
        condition: service_started

  backend:
    build: ./backend
    ports:
      - '5001:5000'
    environment:
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/mydatabase'
      # Add this line for the MongoDB connection string
      MONGO_DATABASE_URL: 'mongodb://mongo:27017/'
    depends_on:
      db:
        condition: service_healthy
      # Add this to make the backend depend on mongo
      mongo:
        condition: service_started

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d mydatabase']
      interval: 10s
      timeout: 5s
      retries: 5

  # Add this entire block for the new MongoDB service
  mongo:
    image: mongo:latest # Use the official MongoDB image
    ports:
      - '27017:27017' # Map the port to your host machine for optional access
    volumes:
      - mongo_data:/data/db # Persist MongoDB data

volumes:
  db_data:
  # Add a new volume for MongoDB
  mongo_data:
